from django.core.management.base import BaseCommand
from datetime import date

from checker.models import Scheme

VERIFIED_ON = date(2026, 5, 30)


SCHEMES = [
    {
        "name": "Post Matric Scholarship for SC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "scope": "central",
        "description": "Financial assistance for Scheduled Caste students studying after Class 10.",
        "benefit": "Maintenance allowance, compulsory fees, and other approved academic support.",
        "official_url": "https://scholarships.gov.in/",
        "source_url": "https://socialjustice.gov.in/schemes/25/archive",
        "education_levels": ["class_11_12", "diploma", "undergraduate", "postgraduate", "phd"],
        "categories": ["sc"],
        "max_annual_income": 250000,
        "min_marks_percent": 50,
        "caste_certificate_required": True,
        "documents_required": "Caste certificate, income certificate, previous marksheet, Aadhaar, bank passbook.",
        "application_steps": "Register on National Scholarship Portal, complete profile, select scheme, upload documents, submit to institution.",
        "deadline_note": "Check NSP for current academic year deadline.",
    },
    {
        "name": "Post Matric Scholarship for ST Students",
        "provider": "Ministry of Tribal Affairs",
        "scope": "central",
        "description": "Support for Scheduled Tribe students pursuing post-matric education.",
        "benefit": "Academic fees and maintenance allowance as per course group.",
        "official_url": "https://scholarships.gov.in/",
        "source_url": "https://tribal.nic.in/Scholarship.Aspx",
        "education_levels": ["class_11_12", "diploma", "undergraduate", "postgraduate", "phd"],
        "categories": ["st"],
        "max_annual_income": 250000,
        "min_marks_percent": 50,
        "caste_certificate_required": True,
        "documents_required": "Tribe certificate, income certificate, marksheet, Aadhaar, bank details.",
        "application_steps": "Apply through NSP or state scholarship portal, depending on notification.",
        "deadline_note": "Usually announced yearly by NSP/state portal.",
    },
    {
        "name": "AICTE Pragati Scholarship for Girl Students",
        "provider": "AICTE",
        "scope": "central",
        "description": "Scholarship for girl students admitted to technical diploma or degree courses.",
        "benefit": "Tuition fee assistance and incidental allowance as per AICTE rules.",
        "official_url": "https://www.aicte-india.org/",
        "source_url": "https://aicte-qa.aicte-india.org/sites/default/files/Final%20FAQ.pdf",
        "education_levels": ["diploma", "undergraduate"],
        "course_streams": ["technical", "engineering"],
        "genders": ["female"],
        "max_annual_income": 800000,
        "min_marks_percent": 50,
        "documents_required": "Admission proof, income certificate, marksheets, bank details, Aadhaar.",
        "application_steps": "Apply through NSP when AICTE Pragati window is open.",
        "deadline_note": "Check AICTE/NSP announcement.",
    },
    {
        "name": "AICTE Saksham Scholarship for Students with Disabilities",
        "provider": "AICTE",
        "scope": "central",
        "description": "Scholarship for specially-abled students in AICTE-approved technical courses.",
        "benefit": "Tuition fee support and incidental allowance.",
        "official_url": "https://www.aicte-india.org/",
        "source_url": "https://aicte-qa.aicte-india.org/sites/default/files/Final%20FAQ.pdf",
        "education_levels": ["diploma", "undergraduate"],
        "course_streams": ["technical", "engineering"],
        "max_annual_income": 800000,
        "min_marks_percent": 50,
        "disability_required": True,
        "disability_certificate_required": True,
        "documents_required": "Disability certificate, admission proof, income certificate, marksheet, bank details.",
        "application_steps": "Apply through NSP during the Saksham scheme application period.",
        "deadline_note": "Check NSP for current cycle.",
    },
    {
        "name": "Telangana Post Matric Scholarship",
        "provider": "Government of Telangana",
        "scope": "state",
        "description": "Fee reimbursement and scholarship support for eligible Telangana students.",
        "benefit": "Tuition fee reimbursement and maintenance support based on course/category.",
        "official_url": "https://telanganaepass.cgg.gov.in/",
        "source_url": "https://telanganaepass.cgg.gov.in/downloads/SCDD-RTIManual.pdf",
        "eligible_states": ["telangana"],
        "education_levels": ["class_11_12", "diploma", "undergraduate", "postgraduate"],
        "categories": ["sc", "st", "obc", "ews", "minority"],
        "max_annual_income": 200000,
        "min_marks_percent": 50,
        "max_age": 34,
        "caste_certificate_required": True,
        "documents_required": "Caste certificate, income certificate, bonafide certificate, previous marksheet, bank passbook.",
        "application_steps": "Apply on Telangana ePASS, complete student details, upload documents, and submit through institution.",
        "deadline_note": "Check Telangana ePASS notifications.",
    },
    {
        "name": "National Means-cum-Merit Scholarship",
        "provider": "Department of School Education and Literacy",
        "scope": "central",
        "description": "Scholarship for meritorious students from economically weaker sections to reduce dropout after Class 8.",
        "benefit": "Annual scholarship amount as notified by the government.",
        "official_url": "https://scholarships.gov.in/",
        "source_url": "https://scholarships.gov.in/",
        "education_levels": ["class_9_10", "class_11_12"],
        "max_annual_income": 350000,
        "min_marks_percent": 55,
        "documents_required": "Income certificate, school certificate, marksheet, bank details, Aadhaar.",
        "application_steps": "Qualify the NMMS exam and complete application through NSP as per state process.",
        "deadline_note": "State exam and NSP dates vary each year.",
    },
    {
        "name": "Pre-Matric Scholarship for SC Students",
        "provider": "Department of Social Justice and Empowerment",
        "scope": "central",
        "description": "Support for Scheduled Caste students studying in Classes 9 and 10.",
        "benefit": "Academic allowance as notified for day scholars and hostellers.",
        "official_url": "https://socialjustice.gov.in/schemes/23/archive",
        "source_url": "https://socialjustice.gov.in/schemes/23/archive",
        "education_levels": ["class_9_10"],
        "categories": ["sc"],
        "max_annual_income": 250000,
        "min_marks_percent": 50,
        "caste_certificate_required": True,
        "documents_required": "Caste certificate, income certificate, school certificate, bank details, Aadhaar where required.",
        "application_steps": "Apply through the notified national or state scholarship portal for the academic year.",
        "deadline_note": "Check official portal notification.",
    },
    {
        "name": "Pre-Matric Scholarship for ST Students",
        "provider": "Ministry of Tribal Affairs",
        "scope": "central",
        "description": "Scholarship for Scheduled Tribe students in Classes 9 and 10.",
        "benefit": "Monthly scholarship support for eligible day scholars and hostellers.",
        "official_url": "https://tribal.nic.in/Scholarship.Aspx",
        "source_url": "https://tribal.nic.in/Scholarship.Aspx",
        "education_levels": ["class_9_10"],
        "categories": ["st"],
        "max_annual_income": 250000,
        "min_marks_percent": 50,
        "caste_certificate_required": True,
        "aadhaar_linked_bank_required": True,
        "documents_required": "ST certificate, income certificate, school certificate, Aadhaar-linked bank account details.",
        "application_steps": "Apply through State/UT or National Scholarship Portal as notified.",
        "deadline_note": "Check State/UT scholarship notification.",
    },
    {
        "name": "PM YASASVI Post Matric Scholarship for OBC, EBC and DNT Students",
        "provider": "Department of Social Justice and Empowerment",
        "scope": "central",
        "description": "Post-matric support for OBC, EBC and DNT students under PM YASASVI.",
        "benefit": "Maintenance allowance and approved fee support as per scheme rules.",
        "official_url": "https://scholarships.gov.in/",
        "source_url": "https://www.socialjustice.gov.in/social-audit/schemes",
        "education_levels": ["class_11_12", "diploma", "undergraduate", "postgraduate"],
        "categories": ["obc", "ews"],
        "max_annual_income": 250000,
        "min_marks_percent": 50,
        "caste_certificate_required": True,
        "documents_required": "Category certificate, income certificate, marksheet, institution certificate, bank details.",
        "application_steps": "Apply through NSP or state portal when the scheme window opens.",
        "deadline_note": "Check NSP/current state notification.",
    },
    {
        "name": "Central Sector Scheme of Scholarship for College and University Students",
        "provider": "Department of Higher Education",
        "scope": "central",
        "description": "Merit-cum-means scholarship for college and university students based on Class 12 performance.",
        "benefit": "Annual financial support for eligible undergraduate and postgraduate study.",
        "official_url": "https://scholarships.gov.in/",
        "source_url": "https://scholarships.gov.in/",
        "education_levels": ["undergraduate", "postgraduate"],
        "max_annual_income": 450000,
        "min_marks_percent": 80,
        "documents_required": "Class 12 marksheet, income certificate, admission proof, bank details, Aadhaar where required.",
        "application_steps": "Apply or renew through National Scholarship Portal.",
        "deadline_note": "Check NSP for fresh and renewal deadlines.",
    },
    {
        "name": "Telangana Overseas Scholarship",
        "provider": "Government of Telangana",
        "scope": "state",
        "description": "Financial assistance for eligible Telangana students pursuing higher education abroad.",
        "benefit": "Grant up to the amount notified by Telangana ePASS for overseas study.",
        "official_url": "https://telanganaepass.cgg.gov.in/OverseasLinks.do",
        "source_url": "https://telanganaepass.cgg.gov.in/OverseasLinks.do",
        "eligible_states": ["telangana"],
        "education_levels": ["postgraduate", "phd"],
        "categories": ["sc", "st", "obc", "minority"],
        "max_annual_income": 500000,
        "min_marks_percent": 60,
        "max_age": 35,
        "course_streams": ["technical", "medical", "engineering", "research", "general"],
        "caste_certificate_required": True,
        "documents_required": "Admission letter, passport, income certificate, category certificate, qualifying exam score, bank details.",
        "application_steps": "Apply through Telangana ePASS overseas scholarship services.",
        "deadline_note": "Check Telangana ePASS overseas notifications.",
    },
]


class Command(BaseCommand):
    help = "Seed the database with initial scholarship schemes."

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for data in SCHEMES:
            defaults = {
                "academic_year": "2025-26",
                "last_verified_on": VERIFIED_ON,
                "income_certificate_required": True,
                "previous_year_pass_required": True,
                "bank_account_required": True,
            }
            defaults.update(data)
            scheme, was_created = Scheme.objects.update_or_create(
                name=data["name"],
                defaults=defaults,
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(f"Seeded schemes: {created} created, {updated} updated."))
