# Generated by Django 5.0.8 on 2026-05-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='aadhaar_linked_bank_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='academic_year',
            field=models.CharField(default='2025-26', max_length=20),
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste_certificate_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='course_streams',
            field=models.JSONField(blank=True, default=list, help_text='Empty means all course streams'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='day_scholar_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='disability_certificate_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='hosteller_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='income_certificate_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='institution_types',
            field=models.JSONField(blank=True, default=list, help_text='Empty means all institution types'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='last_verified_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='previous_year_pass_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='aadhaar_linked_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course_stream',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical / Professional'), ('medical', 'Medical'), ('engineering', 'Engineering'), ('vocational', 'Vocational'), ('research', 'Research')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domicile_state',
            field=models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('puducherry', 'Puducherry')], default='telangana', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_caste_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_disability_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_income_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_type',
            field=models.CharField(choices=[('government', 'Government'), ('aided', 'Government Aided'), ('private', 'Private'), ('deemed', 'Deemed University')], default='government', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_year_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='residence_type',
            field=models.CharField(choices=[('day_scholar', 'Day Scholar'), ('hosteller', 'Hosteller')], default='day_scholar', max_length=20),
        ),
    ]
